### ISSUE TITLE
Failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'

### ISSUE THREAD

**Issue by VS3CT** [Senophyx/Discord-RPC#29]
I'm aware this is only an error you'd see if you aren't on Linux, and as said on another issue, I tried other versions but it still returned the same error. I'm on windows btw

**Comment by Senophyx** [comment]
Most likely, the error occurs because Discord is not yet running or even installed.

If you look at the code at [presence.py#138](https://github.com/Senophyx/Discord-RPC/blob/875eb05f84ffab4543ecca89d3af1de95fc111df/discordrpc/presence.py#L138), Discord-RPC opens the Discord pipe socket. Therefore, if Discord is not already running, Discord-RPC will not run correctly.

**Comment by Senophyx** [comment]
Closed, since there is no further confirmation.
